databases:
  - name: FUMIDASU1_DB
    databaseName: FUMIDASU1_db
    user: FUMIDASU1
    region: singapore

services:
  - type: web
    name: FUMIDASU1
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: FUMIDASU1_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

